# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  webapp:
    image: paulyk/web-app-docker-demo
    build:
      context: .
      dockerfile: Web.App/Dockerfile
    ports:
      - 5000:5000
